### ISSUE TITLE
Handle animation vertex data

### ISSUE THREAD

**Issue by freezy** [freezy/VisualPinball.Engine#125]
Forgot about that, those are completely ignored for now. Tags `M3AY` and `M3AX`. A table containing those is `AC-DC_Premium-1.4`.

Need to read more into vertex animation and how this is done in Unity.

**Comment by ecurtz** [comment]
You can either add blendshapes as part of the mesh creation, or dynamically update the mesh vertices (which is slow, but less terrible since they've recently improved the API) depending on exactly what the tags are representing. Is there a reference for the tags somewhere? I couldn't find one.

**Comment by ecurtz** [comment]
I found it in the VPinball repository. It looks like it's interpolating between vertex and normal data with a complete set in each "frame": https://github.com/vpinball/vpinball/blob/00452216b14d5fe4c1a9c5606d342ce689e86f86/primitive.cpp

It would be a bit of a hack but simple and reasonably performant to do this as a single blendshape with multiple frames: https://docs.unity3d.com/ScriptReference/Mesh.AddBlendShapeFrame.html

This would allow a trivial update which simply set the blendshape weight and the actual mesh update math would be done on the GPU.

**Comment by freezy** [comment]
Sounds good! Want to have a go at it? :)

**Comment by freezy** [comment]
Fixed in #167. Thanks @ecurtz!
