### ISSUE TITLE
Adding Package.json in Unity

### ISSUE THREAD

**Issue by JosephGopfton** [freezy/VisualPinball.Engine#133]
I have just downloaded Unity 2020.1.of1 and attempted to add Package.json with Unities Package manager.
Script Error Report
! Cannot perform upm operation. One or more dependencies could not be added to the local file.
! Error adding package. UnityEditor.EditorApplication_CallupdateFunctions()

**Comment by jsm174** [comment]
I just installed Unity 2020.1.0f1 and added the package with no issues. 

Can you elaborate a little more on what you did, ie:

1) git clone git@github.com:freezy/VisualPinball.Engine.git 
2) open unity hub
3) new project with Unity 2020.1.0f1
4) Window -> Package Manager -> + -> Add From Disk -> Select package.json from step 1

Also maybe the log files (https://docs.unity3d.com/Manual/LogFiles.html) might have some more info.

**Comment by freezy** [comment]
Yup, it works for all of us, so we need detailed information of what you were doing exactly. :)

**Comment by JosephGopfton** [comment]
Dear jsm174,
                      Unity Log files resolved the issue.
                      The log referred to firewall issues and not able to reach the download site.
                      I was  offline during the first attempt 
                      During the second attempt  from windows / Package Manager  i selected add package from Git URL
                      Unity now has the packege 
                     Thank you for the time you spent with this issue

**Comment by jsm174** [comment]
Great. Glad it's working!!
