### ISSUE TITLE
Patcher Refinements

### ISSUE THREAD

**Issue by Roland09** [freezy/VisualPinball.Engine#145]
### Patch file detection

Currently the patch file is determined by meta tags. This isn't fine granular enough, e. g. the Tom & Jerry table has the wrong meta tags:

`[MetaMatch(TableName = "Beach Bums (HH Mod - Gottlieb 1986)", AuthorName = "Retro Bash")]`

However the table's name is `TomandJerry` which can in addition to the `MetaMatch` be used to get the proper patch file.

### Access to Primitive data

There needs to be a re-parenting of gameobjects. In order for that to work, one also needs to apply the transform of the Primitive. That data isn't available in the patcher, it should be handed over in addition to the gameobject.

### Patching children

The Tom & Jerry table has a gameobject `Ramp20` which has children `LeftWall`, `RightWall`, etc. The way it is now one has to set NameMatch to `Ramp20` and the code in the patching methoc would be applied to all the children, not just a selected one.

This should be made finer granular, e. g. `Ramp20/LeftWall`. Of course only optionally. `Ramp20` should still select all children.

### Disable patching during Import

I added a parameter `applyPatch` to the importer, but it's unclear where to put that if-code in order to not apply a patch. For one because at certain places the importer uses local methods, for the other it uses static methods.

### Graphics Pipeline

Depending on the graphics pipeline one has to set different shader properties. Should we distinguish by creating a dedicated file for the graphics pipeline? Or a common interface which allows to set e. g. a material to be double sided. In HDRP this might look like this:

```
[NameMatch("Primitive66")] // jerry at plunger
public void SetDoubleSided(GameObject gameObject)
{
	var unityMat = gameObject.GetComponent<Renderer>().sharedMaterial;

	unityMat.EnableKeyword("_DOUBLESIDED_ON");
	unityMat.EnableKeyword("_NORMALMAP_TANGENT_SPACE");

	unityMat.SetInt("_DoubleSidedEnable", 1);
	unityMat.SetInt("_DoubleSidedNormalMode", 1);

	unityMat.SetInt("_CullMode", 0);
	unityMat.SetInt("_CullModeForward", 0);
}
```

Which is way too much code to be duplicated per patch file and hence a common HDRP class with SetDoubleSided(...) might be the better solution.

We should decide in advance, this will have far reaching consequences.

**Comment by freezy** [comment]
Thanks, good stuff. Two questions:

1. Patching children: You'll get the parent `GameObject`, why can't you just get the child from the parent if necessary? I mean, is it just a convenience thing, or have I misunderstood something?
2. Graphics Pipeline: You're free to organize your classes however you'd like. So you can create a class per render pipeline, which inherits from a base class with the helpers you need, or you can do it in one class with other helpers that work for both. In any case, obtaining the pipeline and being able to match against it would be a good addition.

**Comment by Roland09** [comment]
ad 1) It's more readable and less code to specify via annotation than to manually get each child separately in code and in addition apply code on them
ad 2) ok, I'll come up with something and show for the next iteration of discussion

**Comment by freezy** [comment]
I'll create a PR after more testing, but [here](https://github.com/freezy/VisualPinball.Engine/tree/patcher/enhancements)'s already a branch that should address most of the issues. Particularly [this part](https://github.com/freezy/VisualPinball.Engine/tree/patcher/enhancements/VisualPinball.Unity/VisualPinball.Unity.Patcher#patcher) where you now can pick the data you're interested in.
