### ISSUE TITLE
Layer Manager Improvements

### ISSUE THREAD

**Issue by freezy** [freezy/VisualPinball.Engine#150]
There are a few things in the layer manager I'd like to be improved:

- [x] When opened, it should always expand the layers.
- [x] Clicking on the plus icon, should prompt for a layer name. When added, the new layer should be selected.
- [x] Same when right-clicking on a game item and selecting *assign to / new layer*: Prompt name and select created layer.
- [x] Dragging a game object from the Hierarchy into a layer doesn't work.
- [x] Remove the *Select only game items to enable layer assignment* menu when right-clicking on a layer, I find it confusing
- [x] Only show *new layer* when right-clicking on the top table node
- [x] Only show *delete layer* when right-clicking on a layer
- [x] When adding a new item with the toolbox, the item should be added to the currently selected layer (or, if an item is selected, the layer of the item). When multiple layers are selected, the first layer should be used.
- [x] Selection management: Double-click to select in the Hierarchy is fine, but what about multiple elements? Let's say an author keeps all GI lights in a layer and want to update their properties simultaneously. Multi-selecting them in the layer and having them multi-selected in the Hierarchy would be nice. Maybe with a right-click menu?
- [x] Selection vol2: What if an item is selected in the hierarchy? How to find it rapidly in the layer manager? Would an auto-select in layer manager when selection changes in the hierarchy be possible?

**Comment by Vroonsh** [comment]
About double click selection.
Double clicking on a layer or even the table is already selecting all related items in the Scene Hierarchy.

Will see if Layer Editor selection synchronization is possible.
