### ISSUE TITLE
GPL variant choice is not clear (GPLv2-only or GPLv2-or-later)

### ISSUE THREAD

**Issue by JayFoxRox** [freezy/VisualPinball.Engine#160]
It's not very obvious if this project is licensed under GPLv2-only or GPLv2-or-later.
The guidelines from the GPL about how to apply the license don't seem to be respected.

However, this might be irrelevant because of #159 which documents other GPL issues.

**Comment by freezy** [comment]
It's pretty clear, it's GPLv2-only. But let's take this to #159.
