### ISSUE TITLE
Manage switches and key events

### ISSUE THREAD

**Issue by freezy** [freezy/VisualPinball.Engine#185]
We need to abstract switches. Switches can be playfield items and key presses. The reason we need to abstract them is to easily hook them up with game logic. PinMAME for example doesn't care whether a switch came from a cabinet button or from the playfield.

## Playfield Switches

There are some game items that act as switches, namely:

- Triggers: The `Hit` and `UnHit` events enable and disable the switch.
- Bumpers: The `Hit` event enables and disables the switch. But they directly trigger the coil as well.
- Spinners: They close a switch once per rotation. Events are `LimitBos` and `LimitEos`.
- Gates: One-way gates emit `Hit` when the ball rolls through (not when blocked). Two-way gates emit `Hit` twice, when entering and leaving. 
- Kicker: Gets a `Hit` event as well when the ball goes into it.
- Targets: A `Hit` event as well.
- Others: Any game item can emit events, for example a slingshot trigger is typically a wall with a slingshot segment and needs to be managed as switch as well.

## Cabinet Switches

Cabinet switches are typically buttons somewhere outside of the cabinet. Off the top of my head, those are things like:

- Flipper buttons (left and right)
- Magnasave (left and right)
- Start button
- Plunger button
- Menu buttons in the coin door (typically four)
- Special buttons (cannon button, etc)

I would use [Unity's new input system](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/index.html). It allows mapping keyboard/mouse/controller events to what they call *Actions*. For that they use *Action Maps*. I would suggest creating a *Cabinet Switches* action map and add the switches above as actions (in the future we'll have additional action maps for nudging, plunging etc that are mech- and not game logic-related).

## Other Switches

Looking at the manuals, sometimes switches just need to be set constantly "on".

# Editor

We would like VPE to provide a UI to configure the switches. Manuals typically provide the switches as a matrix, but I think a table would be a better choice. Something along those lines:

![switch-manager](https://user-images.githubusercontent.com/70426/92412276-969e0100-f14b-11ea-84f4-e79abb36812b.png)

What's important to note is that the switches manager is linked to a game logic engine (PinMAME/MPF/etc). It's the game logic engine that defines which switches it expects.

- **ID** - The game logic engine's identifier of the switch. The game logic engine has a method for retrieving switch IDs. Although, it might doesn't know, so we should be easily capable of transforming this into a free text field.
- **Description** - A user value. Typically what it's called in the manual. Ignore the icon for now ;)
- **Source** - Three possible choices, which change the fields of the remaining columns: *Input System*, *Playfield* and *Constant*.
- **Element** - Which within the source it is. For the input system we would list the actions of the cabinet buttons action map. For playfield it could be any game item. For constant it's the value of the constant.
- **Type** - Same for playfield element and input system. *On/Off* means opening and closing the switch needs two events. *Pulse* auto-closes after n milliseconds. 
- **Trigger** - Which element closes the switch.
- **Off** - For On/Off types, here goes the second event. For pulse switches we specify after which time the switch is opened again

# Data

The above needs to be stored somewhere. That's still up to define. We'll need more of this type of data in the future, and storing it in a VPX-compatible way would be nice, for example as a JSON file within VPX' custom attributes. We still don't have defined a way to extend the `.vpx` format, so it can be a temporary thing as well.

# API

Once the data is set, we can use it to hook up the switches to the game logic. The game logic would be a new interface that the PinMAME/MPF plugin would implement. For switches we could have a method like `SetSwitch(string name, bool value)` and `SetSwitch(string name, bool value, int durationMs)`.

Finally, note that we'll need to do the same for solenoids and lights, so classes should be designed in a way they can be easily abstracted.

**Comment by ecurtz** [comment]
If the names are going to be exported for scripting they should either have some constraints or there should be a separate scripting name. If they are only internal / imported then that's not a concern.
Real pinball hardware has some switches (such as optos) which are NC, for normally closed. I'm not sure exactly how that matches up with "Hit" and "UnHit" but might need some thought and a way to be marked.
Trigger and Off for Input System switches will probably need to be implemented as "actions" and connected to the actual keyboard, button, etc. separately, but that may not be possible to show in the mockup.

**Comment by freezy** [comment]
I don't think the names would be exposed anywhere but in the manager. They serve more like as a description (and maybe we should name them  like that). You wouldn't actually need to access them via scripting, and if you really need to trigger a switch per script you can do it via the game item or the engine interface directly.

**Comment by freezy** [comment]
**Bonus feature**: Add a "Populate All" button that adds rows for all IDs, searches for playfield items named the same (if ID is numeric, search for `sw{id}`), sets it to *Playfield* / *{found element}* / *On/Off* / *Hit* / *UnHit* if `UnHit` available, otherwise *Pulse*, or to constant if not found.

**Comment by freezy** [comment]
Closed by #196.
