### ISSUE TITLE
VipsException: unable to call hist_find pngload_buffer

### ISSUE THREAD

**Issue by freezy** [freezy/VisualPinball.Engine#210]
Reported when importing Creature from the black lagoon v1.3.

**Comment by kleisauke** [comment]
I guess it's failing on this line?
https://github.com/freezy/VisualPinball.Engine/blob/9a855fba76595a223ba23f1076037eb0b021beb5/VisualPinball.Engine/VPT/Texture.cs#L141

The only thing I can think of is that `image.Bands < 4`, but that will already be handled by the if-statement before that line. Perhaps the PNG to import is somehow corrupted?

**Comment by jsm174** [comment]
We should probably check this again as this was a long time ago and we are way newer NetVips + Native.

**Comment by jsm174** [comment]
I just pulled cftbl 1.3 from vpforums. I was able to import with no issues. We can close this issue.

(note for myself, will update netvips from 2.0.1/8.12.0-rc1 to 2.1.0/8.12.1 is a future PR)
