### ISSUE TITLE
Add scene setup menu option.

### ISSUE THREAD

**Issue by Pandelii** [freezy/VisualPinball.Engine#218]
Add a scene setup menu that provides a basic preset scene structure allowing early testers to skip setting a bunch of random values.  

- Detect URP/HDRP and apply appropriate presets. 
- Provide basic quality options, preferably tied in with Unity quality settings. (Setup in pipeline configuration presets) 
- Provide DXR setup option. 
- Adjust camera clipping planes.. 
- Add key light and adjust shadow planes
- Option to remove sky environment. On by default. 
-Stretch goal: provide basic additive scene load room preset for testing room environments.

**Comment by freezy** [comment]
I'm wondering if creating a new repo for this would be more appropriate. You're basically starting work for the host application, i.e. the player app. VPE itself is just the package.

What do you think?

**Comment by Pandelii** [comment]
Yeah, I think that makes sense.

**Comment by freezy** [comment]
So, given HDRP is the priority but want to support built-in and URP as well, how would you set this up? One repo with three project folders? Three repos? I assume there is going to be a least parts of the code shared among the different RPs?

**Comment by Roland09** [comment]
Setup would be easy, maintenance not so much. I guess one has to evaluate the pros and cons. I use 3 different projects for testing and eventually always create a new one for eg beta versions of Unity (including HDRP 8, 9 and 10). 

However since most evolves currently around hdrp and rather nothing changes with built-in i'd got with 3 different example project repositories. Independent of VPE. 

Simply just to get started with an initial setup.

**Comment by Pandelii** [comment]
The closest analog I have any experience with is multi-platform projects.  Most of the products I've worked on that had multiple targets tended to follow a similar setup:  The master repo, the primary platform dev repo (HDRP in this case) and then target and feature specific branches and release branches.  The majority of the work was done on the primary platform dev and then anything incompatible was ported to the dev target branches.   Aside from that it followed what I imagine is a standard dev->test->release flow.  Engine upgrades, feature work that spanned multiple release cycles or potentially disruptive work was done in a separate branch and merged back to dev once stable.  

That being said, these were all larger teams working in perforce, so I'm not sure how applicable that structure is in a git environment with a smaller team so whatever you think is best sounds good to me.  

The basic structure looked kind of like this 

Main Repo
- Release
-- Release Target X 
- Test
-- Test Target X 
- Dev
-- Dev Target X 
-- Feature X 
-- Engine Update 
 
Flow was generally:  
Dev -> Dev Target -> Test & Test Target -> Release & Release Target

**Comment by freezy** [comment]
Sounds good. How about creating branches for engine updates, and keeping HDRP/URP/built-in in separate folders?

**Comment by Pandelii** [comment]
Yeah, that sounds good to me.    

In reading up on it some, it looks like they plan have complete interoperability between HDRP and URP this year. I wonder if it is worth supporting the built-in render pipeline at this point.  It is slower than the URP and does not appear to be actively updated from what I can tell.   While URP hasn't reached complete parity with the built in renderer, it appears to be very close. 

https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@10.0/manual/universalrp-builtin-feature-comparison.html

  It seems like they are attempting to replace it with UPR and HDRP.   But if you have a specific reason for wanting to support it I'm not opposed to it at all.

**Comment by Pandelii** [comment]
Just for additional information many of the unsupported features will never be supported because they are either outdated technology or have been replaced by alternate approaches.  I've compiled a list of the differences in case it helps.  

Flare layer:  No longer needed due to the VFX graph support.  Old flare layer was slow to render and limited in function. 

Depth+Normals: I'm not sure exactly what they are referring to here but I think they are referring to a combined depth and normals buffer in the gbuffer.  I need to research this more. 
Shading: Multi-pass vs Single Pass.  Multi-pass is more flexible for very specific circumstances but is slower overall.  Unreal uses only single pass for example.
  
Light limit:  Refers to forward rendering only.  While it claims the built in was unlimited, this is not accurate.  There has always been a hardware imposed limit.  They would allow you to exceed this, but it still wouldn't render the light or would tank performance depending on platform.  

SH Lights:  This refers to Spherical Harmonics which is an approach used in real-time global illumination type effects.  This can be achieved using other methods.  

Light types: 1 Directional light is a standard limitation shared by Unreal.  That they ever supported more than one was actually pretty impressive but not very performant.  The biggest loss there is the In Research point light.  But at the same time, how limiting that is depends on the spot light.  A point light in deferred rendering is a spot light with a 360 FOV so it tends to be cheaper to model them as spot lights.  But all of them also normally support point lights so I'm not sure what the issue is with those in URP.  

Enlighten:  Old, commercial software, not necessary for this project. 

Shadow Mask and Distance Shadow mask are both types of mixed light shadowing (baked/realtime mix).   
Proxy Volume LPPV:  LPPV is the realtime gi light probe setup that is used in the traditional and hdrp pipes.  Its very useful and nice.  Its absence is likely tied to the lack of spherical harmonics but is very unfortunate.   

Halo: No longer necessary.  Old very poorly implemented feature that I've disabled on every project I've shipped in unity because someone wanted to put a glow on a thing.  

Lens Flare:  No longer necessary the way they implemented it.  See Flare Layer above.  
Projector:  Oddly I don't get why this isn't supported yet.  It is neither difficult nor especially expensive in any kind of pipeline.  I can only imagine they haven't got around to it yet.  

Surface Shaders:  Outdated tech.  

Detail Map, Detail Normal Map, Heightmap:  These are all shader related things that are easy to extend support for.  I don't know why they haven't done so.  Its less than a day's work to add.  

Parallax Mapping:  Special use shader type.  Basic level is cheap, advance level uses raymarching and is expensive.  Custom shader can do it simply enough.  

Camera.RenderWithShader:  I will miss it, but it isn't necessary for this project.  
Command buffers in their entirety are no longer necessary in a scriptable render pipeline.  

Auto-exposure:  Most implementations are horrible and tend to see use in projects where you are moving from dark to light environments.  Mostly not applicable for us.  

Screen Space Reflections:  Unless augmented by something else, these usually don't end up looking especially good to begin with.  They are not handled in a physically based manner so tend to negate the benefits of PBR.   But there are other ways of doing reflections like this that can work on low end devices sufficently for our purposes.    

The 8 layer limit is unfortunate.  But not a deal breaker.

**Comment by Pandelii** [comment]
After looking at the roadmap yhe big missing piece to URP is deferred rendering.  I think you are right on continuing to support built-in.  Once they have deferred in beta we coulf re-evaluate.

**Comment by freezy** [comment]
Cool!

I'm hesitant to create the new project right now since it'll add complexity and I'm trying to keep it as simple as possible. @Pandelii could you prioritize maybe #222 for now? If not then no problem, then I'll go ahead and create the player repo.

**Comment by Pandelii** [comment]
Sure thing!

**Comment by Pandelii** [comment]
Closing this one since we decided to go with the asset bundle approach until we get the player/front end work started.
