### ISSUE TITLE
SRP specific refactorings

### ISSUE THREAD

**Issue by Roland09** [freezy/VisualPinball.Engine#220]
It's become necessary to use SRP proprietary classes.

Example: Lights is HDRP proprietary and requires [HD Additional Light Data](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@6.7/manual/Light-Component.html) attached to the light. This in turn requires HDRP specific imports which makes the whole project depend on those.

Suggestion for stepwise refactoring:

* Patcher is currently accessible everywhere => create SRP folder in the patcher, put [RenderPipeline.cs](https://github.com/freezy/VisualPinball.Engine/blob/master/VisualPinball.Unity/VisualPinball.Unity.Patcher/Matcher/RenderPipeline.cs) and the SRP relevant code into it. Use namespace VisualPinball.Unity.SRP
* move the SRP Material Converter parts in there
* move the SRP Ball Material Converter parts in there
* create SRP specific code for light and use it to create the lights in [LightAuthoring.cs](https://github.com/freezy/VisualPinball.Engine/blob/master/VisualPinball.Unity/VisualPinball.Unity/VPT/Light/LightAuthoring.cs)
* all SRP dependent code should use an interface, access should only be via that, e. g. access for light creation `RenderPipeline.Current.CreateLight( GameObject parent)`, access for translucent material creation `RenderPipeline.Current.SetTranslucent( Material material)`

And when all of that is done and works split the SRP classes into dedicated projects where e. g. HDRP proprietary classes can be imported without consequence for Built-in or URP. Or create those projects now and we could split right away.

**Comment by freezy** [comment]
Resolved via [vpe.hdrp](https://github.com/VisualPinball/VisualPinball.Unity.Hdrp) and [vpe.assets.hdrp](https://github.com/VisualPinball/VisualPinball.Unity.AssetLibrary.Hdrp).
