### ISSUE TITLE
Rubbers: Unable to select points for editing.  

### ISSUE THREAD

**Issue by Pandelii** [freezy/VisualPinball.Engine#241]
The points for the rubber shape do not appear to be able to be edited. 

Repro: 
Create Rubber 
Enter edit points mode 
Click on point.  

Expected result:   The point is selected and the widget for editing is displayed.  
Actual result:  No point is selected.

**Comment by freezy** [comment]
@Vroonsh any idea?

**Comment by freezy** [comment]
Should be fine now.
