### ISSUE TITLE
Walls:  Add point has low success rate. 

### ISSUE THREAD

**Issue by Pandelii** [freezy/VisualPinball.Engine#244]
Adding points to wall lines has a high failure rate.  Out of 29 tries, it successfully created points 11 times.  It appears to succeed more often when the line of sight to the add location is unblocked by the wall geometry.  

Repro steps:  
Create wall, enter edit mode. 
Right click on line to add point.  

Expected result:  Point is added at current dot indicator on the line.  
Actual result: Point fails to be added in many cases.  

See attached video. 
[PointAddFailure.zip](https://github.com/freezy/VisualPinball.Engine/files/5542834/PointAddFailure.zip)

**Comment by freezy** [comment]
Thanks!

@Vroonsh do you have time to take a look?
