### ISSUE TITLE
Visuals dump

### ISSUE THREAD

**Issue by freezy** [freezy/VisualPinball.Engine#249]

**Comment by freezy** [comment]
![vpe-poster1](https://user-images.githubusercontent.com/70426/99846360-74c2f080-2b76-11eb-881c-7a54b730a04b.jpg)

![vpe-poster2](https://user-images.githubusercontent.com/70426/99846372-7987a480-2b76-11eb-9084-213df57d5da3.jpg)

**Comment by freezy** [comment]
![vpe-square-colored](https://user-images.githubusercontent.com/70426/101756172-0965a200-3ad6-11eb-8c71-edb751f0f5d5.png)

**Comment by freezy** [comment]
![image](https://user-images.githubusercontent.com/70426/102674479-73491000-4196-11eb-8f7f-68b5d21cdf7e.png)

**Comment by freezy** [comment]
![image](https://user-images.githubusercontent.com/70426/103411324-a82e6d00-4b6f-11eb-8be9-e24ca66a58fd.png)

**Comment by freezy** [comment]
![image](https://user-images.githubusercontent.com/70426/103697881-d3b2bc80-4fa0-11eb-9fd2-cbef9c49a9d7.png)

**Comment by freezy** [comment]
![image](https://user-images.githubusercontent.com/70426/104245799-35719b80-5465-11eb-909a-555487609fe7.png)

![image](https://user-images.githubusercontent.com/70426/104245762-225ecb80-5465-11eb-8a82-95145ad047f4.png)

**Comment by jsm174** [comment]
![image](https://user-images.githubusercontent.com/1197137/120197430-eeefc400-c1ee-11eb-8fa1-265ecb68a643.png)
![image](https://user-images.githubusercontent.com/1197137/120197433-ef885a80-c1ee-11eb-8ad8-d5fa1022e64a.png)
![image](https://user-images.githubusercontent.com/1197137/120197435-ef885a80-c1ee-11eb-8f61-1ea67d0a11e0.png)
![image](https://user-images.githubusercontent.com/1197137/120197437-ef885a80-c1ee-11eb-89d6-d15f6ad29f40.png)
![image](https://user-images.githubusercontent.com/1197137/120197455-f3b47800-c1ee-11eb-8d0a-2e0c640a5e3d.png)
![image](https://user-images.githubusercontent.com/1197137/120197457-f44d0e80-c1ee-11eb-96d4-7603edb446f5.png)
![image](https://user-images.githubusercontent.com/1197137/120197458-f44d0e80-c1ee-11eb-914f-37cbe48673eb.png)
![image](https://user-images.githubusercontent.com/1197137/120197460-f4e5a500-c1ee-11eb-833e-e6fb656b7415.png)
![image](https://user-images.githubusercontent.com/1197137/120197464-f57e3b80-c1ee-11eb-961d-70f7f30b297e.png)
![image](https://user-images.githubusercontent.com/1197137/120198451-185d1f80-c1f0-11eb-9a6b-ea84b22036ad.jpg)

**Comment by freezy** [comment]
![image](https://user-images.githubusercontent.com/70426/124973397-c3e96300-e02b-11eb-9318-757e647afbb3.png)

**Comment by freezy** [comment]
![dependencies-urp_dependencies](https://user-images.githubusercontent.com/70426/140660427-d7eed12b-2ae6-4213-a094-26a8d1e9770b.png)

**Comment by freezy** [comment]
![dependencies-urp](https://user-images.githubusercontent.com/70426/140660550-5bfa9486-9e28-4c61-8b6d-9cfc9267ba1e.png)
