### ISSUE TITLE
Create decal rendering system for Universal Render Pipeline 

### ISSUE THREAD

**Issue by Pandelii** [freezy/VisualPinball.Engine#253]
The URP does not support decals at the moment.  Since this will likely be a very common approach for table graphics, details and lights, a system will need to be created for adding them.

**Comment by Roland09** [comment]
Unity added Decal improvements for URP and HDRP in the latest alpha releases.

URP:

https://portal.productboard.com/unity/1-unity-platform-rendering-visual-effects/c/33-decals

HDRP:

https://portal.productboard.com/unity/1-unity-platform-rendering-visual-effects/c/603-decal-ux-improvements

**Comment by freezy** [comment]
Looks like it's in: https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@12.0/manual/renderer-feature-decal.html

Closing :)
