### ISSUE TITLE
Dmd  enable/disable

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#321]
There needs to be a public variable that can be changed in the inspector to turn off the dmd so the table can be test when editing a table to test the scripts and physics of the table.

**Comment by freezy** [comment]
Could you be more specific please? Which inspector? What's your use case?

**Comment by shntat** [comment]
The inspector is the window that shows the settings and stuff attached to a game object.
a public variable shows up in the inspector in unity.
what i was referring to is having an option to disable the dmd0 gameobject.
![image](https://user-images.githubusercontent.com/12681995/133348532-e043d827-0203-4901-bbc9-0b621a86ecfa.png)
just to the right of the toolbox is the inspector panel.

**Comment by freezy** [comment]
By "more specific" I don't mean explain how Unity works, but what you're trying to do. ;)

- The inspector changes depending on which object is selected. What I mean by "which inspector" is which object you select where you want to be able to "disable dmd0"?
- Did you actually create a dmd0 game object?
- What do you mean by "disable"? You can already disable any game object in Unity. Do you want to hide it?
- Why did you create it in the first place if you want to "disable" it?

**Comment by shntat** [comment]
no i did not create a dmd or backglass yet. but i did figure out that vpe cannot find a dmd or led display 
I think it is in the public class DisplayPlayer.cs

I get the error below  when i try to build and run the table to test it out.

![dmd error](https://user-images.githubusercontent.com/12681995/133389286-c52c9da2-8592-4214-91cb-b327a1979edd.jpg)

**Comment by freezy** [comment]
Oh you're worried about the message. It's just a warning printed in red and doesn't have any impact.

**Comment by shntat** [comment]
I forgot to say it also crashes when that error pops up in the unity player exe
it also crashes in the editor when you press play saying it ran out  of memory or just throws the error and does not play.

**Comment by freezy** [comment]
Maybe this project isn't mature enough for you yet then. ;)

**Comment by shntat** [comment]
I guess not .
it could be unity acting up again.  📦
