### ISSUE TITLE
Can not get trough to work.

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#324]
Is the ability of the trough to drain and eject balls enabled?
on my table the trough only ejects ball and does not drain them. 
I have tried to use the managers and the inspector settings windows nothing seem to work if i manually setup.

**Comment by freezy** [comment]
When you import VP's blank table, the trough should be automatically set up. That doesn't work for you?

**Comment by freezy** [comment]
Closing, re-open with more details if needed.
