### ISSUE TITLE
org.visualpinball.engine.missionpinball@0.0.1-preview.8 unity 2021.2.3f1

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#342]
only issue i have on 2021.2.3f1

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.8\Runtime\MpfGamelogicEngine.cs(28,51): error CS0535: 'MpfGamelogicEngine' does not implement interface member 'IGamelogicEngine.AvailableWires'

**Comment by shntat** [comment]
This error stops me from running or building table.

**Comment by jsm174** [comment]
This was fixed in: https://github.com/VisualPinball/VisualPinball.Engine.Mpf/pull/8 and https://github.com/VisualPinball/VisualPinball.Engine.Mpf/commit/644c8605c807480678b4fc3d5da7219850d6f053.
