### ISSUE TITLE
missionpinball@0.0.1-preview.9 cannot build player

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#349]
I get this error  in unity 2021.2.4f1

ArgumentException: The Assembly System.Runtime.CompilerServices.Unsafe is referenced by Google.Protobuf ('Packages/org.visualpinball.engine.missionpinball/Plugins/win-x64/Google.Protobuf.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by jsm174** [comment]
Hmm. We may have to go back to packing the DLL with `ilrepack`, but I really don't want to do that.

A super quick google search suggested the following:

`Project Settings -> Player -> Configuration -> Uncheck Assembly Version Validation`

Give that a try and let us know.

**Comment by shntat** [comment]
i turned of the verificaton for netstandard 
I think Google.Protobuf.dll is netstandard version 2.0 not 2.1
unity switched to 2.1 in 2021.2 i believe .I had to update because of an error with a reference to 2.1

https://www.theregister.com/2021/04/13/unity_devs_mull_future_of_dotnet/




ArgumentException: The Assembly System.Runtime.CompilerServices.Unsafe is referenced by Google.Protobuf ('Packages/org.visualpinball.engine.missionpinball/Plugins/win-x86/Google.Protobuf.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <948074e677924ec29383d02747cdda34>:0)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)





UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002d8] in <948074e677924ec29383d02747cdda34>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <948074e677924ec29383d02747cdda34>:0 
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

 

EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

 
-----Original Message-----

**Comment by jsm174** [comment]
Please do not respond to github issues via email. 

> I think Google.Protobuf.dll is netstandard version 2.0 not 2.1
> unity switched to 2.1 in 2021.2 i believe .I had to update because of an error with a reference to 2.1

AFAIK, `netstandard2.0` works totally fine in `netstandard2.1`

The issue is something else. I will research.

**Comment by jsm174** [comment]
Can you try release 10 and report back?

**Comment by shntat** [comment]
ok I got it to build the player no errors
 
 
 
-----Original Message-----

**Comment by freezy** [comment]
Thanks, @jsm174!

**Comment by jsm174** [comment]
@shntat / @fastdraw - again, please do not respond to git issues via email. It puts partial PII in the issue text.
