### ISSUE TITLE
Support for Colored DMDs?

### ISSUE THREAD

**Issue by MavisCelus19201** [freezy/VisualPinball.Engine#378]
Bit of a ways off but is there any chance at supporting colored DMDs in the future? I recall that being the case with FlexDMD and needing to register dlls but if that's ever able to work natively then that's be wicked, kinda the same for some of the B2S backglass setups.

**Comment by freezy** [comment]
Can you be more specific, because today,

- dmdext can set an RGB DMD to any color
- dmdext supports frame-by-frame coloring 

So it's unclear what you exactly mean by "colored DMDs".

**Comment by freezy** [comment]
Oh yeah and obviously we'll support dmdext in VPE. Feel free to close if that was your question ;)

**Comment by MavisCelus19201** [comment]
Closing but dmdext was about what I meant yeah, I recall something being similar with FlexDMD though that might use the former as a base.
