### ISSUE TITLE
Missing drag points

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#379]
Drag points seem to be missing to be able to change the shape of walls and ramps 

![image](https://user-images.githubusercontent.com/12681995/154342276-3fa7cc97-9325-4116-9b60-08ea20c0645b.png)

**Comment by freezy** [comment]
![image](https://user-images.githubusercontent.com/70426/154812586-0eb7a28b-6737-4b49-a9f6-ace428f3bbb6.png)

Click this button.
