### ISSUE TITLE
MaterialConverter does not implement interface member

### ISSUE THREAD

**Issue by Joey-2001** [freezy/VisualPinball.Engine#409]
Library\PackageCache\org.visualpinball.engine.unity.hdrp@0.0.1-preview.145\Runtime\MaterialConverter.cs(37,35): error CS0535: 'MaterialConverter' does not implement interface member 'IMaterialConverter.GetEmissiveIntensity(Material)'

**Comment by freezy** [comment]
Yes, will be fixed when https://github.com/VisualPinball/VisualPinball.Unity.Hdrp/tree/refactor/volley is merged.
