### ISSUE TITLE
We can't assign a new GUID because the asset is in an immutable folder

### ISSUE THREAD

**Issue by Joey-2001** [freezy/VisualPinball.Engine#410]
GUID [c73355b2b8af0ad47b03c3a3797d0a84] for asset 'Packages/org.visualpinball.engine.unity.urp/Assets/Resources/Prefabs/Drop Target - Beveled.prefab' conflicts with:
  'Packages/org.visualpinball.engine.unity.hdrp/Assets/Resources/Prefabs/Drop Target - Beveled.prefab' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

GUID [42880672e6b69e64b980056aa792011d] for asset 'Packages/org.visualpinball.engine.unity.urp/Assets/Resources/Prefabs/Drop Target - Simple Flat.prefab' conflicts with:
  'Packages/org.visualpinball.engine.unity.hdrp/Assets/Resources/Prefabs/Drop Target - Simple Flat.prefab' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

GUID [9505b85583f2ca2448c1ec3521808410] for asset 'Packages/org.visualpinball.engine.unity.urp/Assets/Resources/Prefabs/Drop Target - Simple.prefab' conflicts with:
  'Packages/org.visualpinball.engine.unity.hdrp/Assets/Resources/Prefabs/Drop Target - Simple.prefab' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

GUID [40ea1c392bac0354582c0cee55e10b03] for asset 'Packages/org.visualpinball.engine.unity.urp/Assets/Resources/Prefabs/Hit Target - Narrow.prefab' conflicts with:
  'Packages/org.visualpinball.engine.unity.hdrp/Assets/Resources/Prefabs/Hit Target - Narrow.prefab' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

**Comment by freezy** [comment]
These are warnings, right?

I'm still working on sorting out the assets and get all the repos back to master. Please bear with use a few more weeks until it stabilizes.

**Comment by Joey-2001** [comment]
Yes, it is a warning.
