### ISSUE TITLE
com.unity.jobs@0.8.0-preview.23 2021.3.1f1 broken

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#411]
Library\PackageCache\com.unity.jobs@0.8.0-preview.23\Unity.Jobs\IJobParallelForDefer.cs(77,85): error CS8377: The type 'U' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'

**Comment by crypticC0der** [comment]
i am too having this issue

**Comment by shntat** [comment]
same issue with 106 in editor 2021.3.1f1 and up. It is the only error I have. 
 Library\PackageCache\com.unity.jobs@0.8.0-preview.23\Unity.Jobs\IJobParallelForDefer.cs(77,85): error CS8377: The type 'U' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'  

When i do the online internet fix  i get :    Library\PackageCache\com.unity.entities@0.50.1-preview.2\Unity.Entities\RetainBlobAssetSystem.cs(6,5): error SGICE002: Seeing this error indicates a bug in the dots compiler. We'd appreciate a bug report (About->Report a Bug...). Thnx! <3 System.IO.IOException: Cannot create 'D:\unity project\Munsters LE\Library\Bee\artifacts\1900b0aE.dag\Unity.Entities.AdditionalFile.txt' because a file or directory with the same name already exists.  error CS8377 goes away. 

It seems my project is dead and i cannot do anything with any of these errors present.

**Comment by freezy** [comment]
Latest supported Unity version is 2021.3.0f1, until entities 0.51 comes out.
