### ISSUE TITLE
com.unity.jobs@0.8.0-preview.23 

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#413]
Library\PackageCache\com.unity.jobs@0.8.0-preview.23\Unity.Jobs\IJobParallelForDefer.cs(77,85): error CS8377: The type 'U' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'

**Comment by freezy** [comment]
Will be hopefully fixed when DOTS gets the 0.51 update.
