### ISSUE TITLE
All SystemBase-derived classes must be defined with the `partial` keyword

### ISSUE THREAD

**Issue by shntat** [freezy/VisualPinball.Engine#422]
38 in total with error DC0058
I have included my manifest.json and packages-lock.json files at bottom to show what packages i have installed in 2021.3.6f1

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\ContactSystem.cs(26,2): error DC0058: All SystemBase-derived classes must be defined with the `partial` keyword, so that source generators can emit additional code into these classes. Please add the `partial` keyword to ContactSystem, as well as all the classes it is nested within.

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\DynamicBroadPhaseSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\DynamicCollisionSystem.cs(22,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\DynamicNarrowPhaseSystem.cs(22,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\StaticBroadPhaseSystem.cs(22,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\StaticCollisionSystem.cs(29,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\Collision\StaticNarrowPhaseSystem.cs(25,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\Physics\SystemGroup\SimulateBuildSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Ball\BallDisplacementSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Ball\BallMovementSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Ball\BallRingCounterSystem.cs(22,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Ball\BallSpinHackSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Ball\BallVelocitySystem.cs(27,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Bumper\BumperRingAnimationSystem.cs(22,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Bumper\BumperRingMovementSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Bumper\BumperSkirtAnimationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Bumper\BumperSkirtMovementSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Flipper\FlipperDisplacementSystem.cs(26,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Flipper\FlipperRotateSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Flipper\FlipperVelocitySystem.cs(26,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Gate\GateDisplacementSystem.cs(26,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Gate\GateMovementSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Gate\GateVelocitySystem.cs(26,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\HitTarget\DropTargetAnimationSystem.cs(25,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\HitTarget\DropTargetTransformationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\HitTarget\HitTargetAnimationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\HitTarget\HitTargetTransformationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Plunger\PlungerAnimationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Plunger\PlungerDisplacementSystem.cs(26,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Plunger\PlungerTransformationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Plunger\PlungerVelocitySystem.cs(22,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Spinner\SpinnerDisplacementSystem.cs(28,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Spinner\SpinnerMovementSystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Spinner\SpinnerVelocitySystem.cs(24,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Trigger\TriggerAnimationSystem.cs(23,2)

Library\PackageCache\org.visualpinball.engine.unity@0.0.1-preview.109\VisualPinball.Unity\VisualPinball.Unity\VPT\Trigger\TriggerMovementSystem.cs(23,2)

manifest.json 
{
  "dependencies": {
    "com.unity.collab-proxy": "1.15.18",
    "com.unity.entities": "0.51.0-preview.32",
    "com.unity.feature.development": "1.0.1",
    "com.unity.ide.rider": "3.0.15",
    "com.unity.ide.visualstudio": "2.0.16",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.render-pipelines.high-definition": "12.1.7",
    "com.unity.test-framework": "1.1.31",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.6.4",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualscripting": "1.7.8",
    "org.visualpinball.engine.missionpinball": "0.0.1-preview.15",
    "org.visualpinball.engine.pinmame": "0.0.1-preview.35",
    "org.visualpinball.engine.unity": "0.0.1-preview.109",
    "org.visualpinball.engine.unity.hdrp": "0.0.1-preview.154",
    "org.visualpinball.engine.unity.visualscripting": "0.0.1-preview.10",
    "org.visualpinball.unity.assetlibrary": "0.0.1-preview.53",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  },
  "scopedRegistries": [
    {
      "name": "Visual Pinball Engine",
      "url": "https://registry.visualpinball.org/",
      "scopes": [
        "org.visualpinball"
      ]
    }
  ]
}
packages-lock.json
{
  "dependencies": {
    "com.autodesk.fbx": {
      "version": "4.1.1",
      "depth": 2,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.burst": {
      "version": "1.6.6",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.mathematics": "1.2.1"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.collab-proxy": {
      "version": "1.15.18",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.services.core": "1.0.1"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.collections": {
      "version": "1.3.1",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.burst": "1.6.6",
        "com.unity.test-framework": "1.1.31"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.editorcoroutines": {
      "version": "1.0.0",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.entities": {
      "version": "0.51.0-preview.32",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.burst": "1.6.6",
        "com.unity.properties": "1.7.0-preview",
        "com.unity.properties.ui": "1.7.0-preview",
        "com.unity.serialization": "1.7.0-preview.1",
        "com.unity.collections": "1.3.1",
        "com.unity.mathematics": "1.2.6",
        "com.unity.modules.assetbundle": "1.0.0",
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.test-framework.performance": "2.8.0-preview",
        "com.unity.nuget.mono-cecil": "1.10.1",
        "com.unity.jobs": "0.51.0-preview.32",
        "com.unity.scriptablebuildpipeline": "1.19.2",
        "com.unity.platforms": "0.51.0-preview.31",
        "com.unity.roslyn": "0.2.2-preview",
        "com.unity.profiling.core": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.ext.nunit": {
      "version": "1.0.6",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.feature.development": {
      "version": "1.0.1",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.ide.visualstudio": "2.0.16",
        "com.unity.ide.rider": "3.0.15",
        "com.unity.ide.vscode": "1.2.5",
        "com.unity.editorcoroutines": "1.0.0",
        "com.unity.performance.profile-analyzer": "1.1.1",
        "com.unity.test-framework": "1.1.31",
        "com.unity.testtools.codecoverage": "1.0.1"
      }
    },
    "com.unity.formats.fbx": {
      "version": "4.1.2",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.timeline": "1.5.2",
        "com.autodesk.fbx": "4.1.1"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.ide.rider": {
      "version": "3.0.15",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.ext.nunit": "1.0.6"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.ide.visualstudio": {
      "version": "2.0.16",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.test-framework": "1.1.9"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.ide.vscode": {
      "version": "1.2.5",
      "depth": 0,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.inputsystem": {
      "version": "1.3.0",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.modules.uielements": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.jobs": {
      "version": "0.51.0-preview.32",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.burst": "1.6.6",
        "com.unity.collections": "1.3.1",
        "com.unity.mathematics": "1.2.6",
        "com.unity.nuget.mono-cecil": "1.10.1"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.mathematics": {
      "version": "1.2.6",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.nuget.mono-cecil": {
      "version": "1.10.1",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.nuget.newtonsoft-json": {
      "version": "3.0.2",
      "depth": 2,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.performance.profile-analyzer": {
      "version": "1.1.1",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.platforms": {
      "version": "0.51.0-preview.31",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.properties": "1.7.0-preview",
        "com.unity.properties.ui": "1.7.0-preview",
        "com.unity.scriptablebuildpipeline": "1.19.2",
        "com.unity.serialization": "1.7.0-preview.1"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.profiling.core": {
      "version": "1.0.2",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.properties": {
      "version": "1.7.0-preview",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.nuget.mono-cecil": "0.1.6-preview.2",
        "com.unity.test-framework.performance": "2.3.1-preview"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.properties.ui": {
      "version": "1.7.0-preview",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.properties": "1.7.0-preview",
        "com.unity.serialization": "1.7.0-preview.1",
        "com.unity.modules.uielements": "1.0.0",
        "com.unity.test-framework.performance": "2.3.1-preview"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.render-pipelines.core": {
      "version": "12.1.7",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.ugui": "1.0.0",
        "com.unity.modules.physics": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      }
    },
    "com.unity.render-pipelines.high-definition": {
      "version": "12.1.7",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.mathematics": "1.2.4",
        "com.unity.burst": "1.6.0",
        "com.unity.modules.video": "1.0.0",
        "com.unity.modules.animation": "1.0.0",
        "com.unity.modules.imageconversion": "1.0.0",
        "com.unity.modules.terrain": "1.0.0",
        "com.unity.render-pipelines.core": "12.1.7",
        "com.unity.shadergraph": "12.1.7",
        "com.unity.visualeffectgraph": "12.1.7",
        "com.unity.render-pipelines.high-definition-config": "12.1.7"
      }
    },
    "com.unity.render-pipelines.high-definition-config": {
      "version": "12.1.7",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.render-pipelines.core": "12.1.7"
      }
    },
    "com.unity.roslyn": {
      "version": "0.2.2-preview",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.scriptablebuildpipeline": {
      "version": "1.20.1",
      "depth": 1,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.searcher": {
      "version": "4.9.1",
      "depth": 2,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.serialization": {
      "version": "1.7.0-preview.1",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.collections": "0.12.0-preview.13",
        "com.unity.burst": "1.3.5",
        "com.unity.jobs": "0.5.0-preview.14",
        "com.unity.properties": "1.7.0-preview",
        "com.unity.test-framework.performance": "2.3.1-preview"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.services.core": {
      "version": "1.4.0",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.nuget.newtonsoft-json": "3.0.2",
        "com.unity.modules.androidjni": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.settings-manager": {
      "version": "1.0.3",
      "depth": 2,
      "source": "registry",
      "dependencies": {},
      "url": "https://packages.unity.com"
    },
    "com.unity.shadergraph": {
      "version": "12.1.7",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.render-pipelines.core": "12.1.7",
        "com.unity.searcher": "4.9.1"
      }
    },
    "com.unity.test-framework": {
      "version": "1.1.31",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.ext.nunit": "1.0.6",
        "com.unity.modules.imgui": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.test-framework.performance": {
      "version": "2.8.0-preview",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.test-framework": "1.1.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.testtools.codecoverage": {
      "version": "1.0.1",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.test-framework": "1.0.16",
        "com.unity.settings-manager": "1.0.1"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.textmeshpro": {
      "version": "3.0.6",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.ugui": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.timeline": {
      "version": "1.6.4",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.modules.director": "1.0.0",
        "com.unity.modules.animation": "1.0.0",
        "com.unity.modules.audio": "1.0.0",
        "com.unity.modules.particlesystem": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "com.unity.ugui": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.ui": "1.0.0",
        "com.unity.modules.imgui": "1.0.0"
      }
    },
    "com.unity.visualeffectgraph": {
      "version": "12.1.7",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.shadergraph": "12.1.7",
        "com.unity.render-pipelines.core": "12.1.7"
      }
    },
    "com.unity.visualscripting": {
      "version": "1.7.8",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.ugui": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },
    "org.visualpinball.engine.missionpinball": {
      "version": "0.0.1-preview.15",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "org.visualpinball.engine.unity": "0.0.1-preview.105"
      },
      "url": "https://registry.visualpinball.org"
    },
    "org.visualpinball.engine.pinmame": {
      "version": "0.0.1-preview.35",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "org.visualpinball.engine.unity": "0.0.1-preview.104"
      },
      "url": "https://registry.visualpinball.org"
    },
    "org.visualpinball.engine.unity": {
      "version": "0.0.1-preview.109",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.burst": "1.6.5",
        "com.unity.entities": "0.17.0-preview.42",
        "com.unity.formats.fbx": "4.1.2",
        "com.unity.jobs": "0.8.0-preview.23",
        "com.unity.mathematics": "1.2.5",
        "com.unity.inputsystem": "1.3.0",
        "com.unity.ugui": "1.0.0",
        "com.unity.test-framework": "1.1.31"
      },
      "url": "https://registry.visualpinball.org"
    },
    "org.visualpinball.engine.unity.hdrp": {
      "version": "0.0.1-preview.154",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.render-pipelines.high-definition": "12.1.2",
        "com.unity.render-pipelines.high-definition-config": "12.1.2",
        "org.visualpinball.engine.unity": "0.0.1-preview.109",
        "org.visualpinball.unity.assetlibrary": "0.0.1-preview.53"
      },
      "url": "https://registry.visualpinball.org"
    },
    "org.visualpinball.engine.unity.visualscripting": {
      "version": "0.0.1-preview.10",
      "depth": 0,
      "source": "registry",
      "dependencies": {
        "com.unity.visualscripting": "1.7.7",
        "org.visualpinball.engine.unity": "0.0.1-preview.90"
      },
      "url": "https://registry.visualpinball.org"
    },
    "org.visualpinball.unity.assetlibrary": {
      "version": "0.0.1-preview.53",
      "depth": 0,
      "source": "registry",
      "dependencies": {},
      "url": "https://registry.visualpinball.org"
    },
    "com.unity.modules.ai": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.androidjni": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.animation": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.assetbundle": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.audio": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.cloth": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.physics": "1.0.0"
      }
    },
    "com.unity.modules.director": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.audio": "1.0.0",
        "com.unity.modules.animation": "1.0.0"
      }
    },
    "com.unity.modules.imageconversion": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.imgui": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.jsonserialize": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.particlesystem": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.physics": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.physics2d": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.screencapture": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.imageconversion": "1.0.0"
      }
    },
    "com.unity.modules.subsystems": {
      "version": "1.0.0",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.jsonserialize": "1.0.0"
      }
    },
    "com.unity.modules.terrain": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.terrainphysics": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.physics": "1.0.0",
        "com.unity.modules.terrain": "1.0.0"
      }
    },
    "com.unity.modules.tilemap": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.physics2d": "1.0.0"
      }
    },
    "com.unity.modules.ui": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.uielements": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.ui": "1.0.0",
        "com.unity.modules.imgui": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0",
        "com.unity.modules.uielementsnative": "1.0.0"
      }
    },
    "com.unity.modules.uielementsnative": {
      "version": "1.0.0",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.ui": "1.0.0",
        "com.unity.modules.imgui": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      }
    },
    "com.unity.modules.umbra": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.unityanalytics": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      }
    },
    "com.unity.modules.unitywebrequest": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.unitywebrequestassetbundle": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.assetbundle": "1.0.0",
        "com.unity.modules.unitywebrequest": "1.0.0"
      }
    },
    "com.unity.modules.unitywebrequestaudio": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.modules.audio": "1.0.0"
      }
    },
    "com.unity.modules.unitywebrequesttexture": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.modules.imageconversion": "1.0.0"
      }
    },
    "com.unity.modules.unitywebrequestwww": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
        "com.unity.modules.unitywebrequestaudio": "1.0.0",
        "com.unity.modules.audio": "1.0.0",
        "com.unity.modules.assetbundle": "1.0.0",
        "com.unity.modules.imageconversion": "1.0.0"
      }
    },
    "com.unity.modules.vehicles": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.physics": "1.0.0"
      }
    },
    "com.unity.modules.video": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.audio": "1.0.0",
        "com.unity.modules.ui": "1.0.0",
        "com.unity.modules.unitywebrequest": "1.0.0"
      }
    },
    "com.unity.modules.vr": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.jsonserialize": "1.0.0",
        "com.unity.modules.physics": "1.0.0",
        "com.unity.modules.xr": "1.0.0"
      }
    },
    "com.unity.modules.wind": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {}
    },
    "com.unity.modules.xr": {
      "version": "1.0.0",
      "depth": 0,
      "source": "builtin",
      "dependencies": {
        "com.unity.modules.physics": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0",
        "com.unity.modules.subsystems": "1.0.0"
      }
    }
  }
}

**Comment by shntat** [comment]
Ok I will try a clean install of unity and let you know how it goes on my computer.

**Comment by freezy** [comment]
Not even sure if we'll migrate to .51 -> 1.0 or to 1.0 directly. I might have a look at this in the next few days, but if it's too much of a mess I'll probably migrate when 1.0 comes out end of this year.
