### ISSUE TITLE
Current code version run in Linux ?

### ISSUE THREAD

**Issue by Augusto7743** [freezy/VisualPinball.Engine#446]
Thanks for reading my topic.
Visual Pinball Engine current code version is ready to run in Linux ?
Not demanding , but perhaps in next year will be released the first version ?

Have an good week.

**Comment by freezy** [comment]
It compiles on Linux, but none of us devs is using it as a daily driver. Common perception is that Unity on Linux is less stable than Windows or MacOS. 

Release date: See [WIP thread](https://vpuniverse.com/forums/topic/5362-wip-visual-pinball-in-unity-2021-edition/page/12/#comment-64348).

**Comment by Augusto7743** [comment]
Thanks for your reply.
Well ... Pinball simulation on Linux not are in good status.
Is possible run Visual Pinball using WINE latest version , but the physics are strange and not accurate as if anything not is giving enough time or require several threads not being allowed in WINE. Also some tables crash.
VisualPinball.Engine is an possible solution for Linux.
You believe VisualPinball.Engine in future versions can run all VP tables without any issues ?

Thanks for reading.
Have an nice week.

**Comment by freezy** [comment]
For Visual Pinball, there are efforts to get Linux compatibility as we speak. See [this branch](https://github.com/vpinball/vpinball/tree/standalone).

VPE won't be able to run VP tables, but creators will able to import them into the editor, and it should be relatively trivial to port them. Guides and documentation about this process will follow.
