### ISSUE TITLE
Jobs run synchronously

### ISSUE THREAD

**Issue by arthurkehrwald** [freezy/VisualPinball.Engine#490]
All the jobs I can find in the code are started using [`IJobExtensions.Run`](https://docs.unity3d.com/2022.3/Documentation/ScriptReference/Unity.Jobs.IJobForExtensions.Schedule.html) instead of [`IJobExtensions.Schedule`](https://docs.unity3d.com/2022.3/Documentation/ScriptReference/Unity.Jobs.IJobForExtensions.Run.html). This means they run synchronously on the main thread. Doesn't this defeat the purpose of using jobs?

**Comment by freezy** [comment]
No, as far as I know, it's not possible to run Bursted code without a job. So the job system in our case is not to run many tasks async in parallel, but to get the performance that Burst provides. The physics loop here takes under a millisecond to run, so I'm not even sure the scheduling overhead would be worth making it async and deal with all the side effects that come with it.

**Comment by arthurkehrwald** [comment]
Alright, makes sense.
