### ISSUE TITLE
Editor Support

### ISSUE THREAD

**Issue by rbxnk** [freezy/VisualPinball.Engine#65]
This issue is to track reaching parity with the VPX editor.
Remaining issues:

- [x] Light importer not parenting unity light objects to VP item
- [x] Need to implement light inspector and behavior edit support
- [x] All Items: Visibility toggles
- [x] All Items: Object type drop downs, changing meshes etc
- [x] All Items with children: Visibility toggles for each child (e.g. bumper skirt)
- [x] Bumper needs rotation gizmo
- [x] Drag point support - this would cover ramps, rubbers, surfaces (#75)
- [x] 3d rotation gizmo doesn't appear to be working on the correct axis in all cases
- [x] -"Toolbox" window for creating new items in the table (own ticket, #76)-

**Comment by freezy** [comment]
Great stuff, made your list TODOable so we can check them off :)
